## WHAT IS PYTORCH?

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

In [6]:
# Construct a 5x3 matrix, uninitialized:
def torch_uninitialize():
    x = torch.empty(5, 3)
    print(x)
    
torch_initialize()

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8217e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [7]:
# Construct a randomly initialized matrix:
def torch_random_initialize():
    x = torch.rand(5, 3)
    print(x)
    
torch_random_initialize()

tensor([[0.8621, 0.2013, 0.6311],
        [0.1025, 0.3390, 0.7255],
        [0.0917, 0.1638, 0.5776],
        [0.4536, 0.8610, 0.7851],
        [0.2457, 0.4535, 0.8394]])


In [8]:
# Construct a matrix filled zeros and of dtype long:
def torch_zero():
    x = torch.zeros(5, 3, dtype=torch.long)
    print(x)
    
torch_zero()

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
# Construct a tensor directly from data:
def create_tensor():
    x = torch.tensor([5.5, 3])
    print(x)
    return x
    
x = create_tensor()

tensor([5.5000, 3.0000])


In [13]:
# Create a tensor based on an existing tensor.
def create_new_ones(x):
    # new_* methods take in sizes
    x = x.new_ones(5, 3, dtype=torch.double)
    print(x)
    return x

x = create_new_ones(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [15]:
# These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
def create_randn_like(x):
    x = x.new_ones(5, 3, dtype=torch.double)
    # override dtype!
    x = torch.randn_like(x, dtype=torch.float)
    print(x)
    return x

x = create_randn_like(x)

tensor([[-0.1173, -0.1209,  1.1584],
        [-0.3393, -0.4896, -1.7425],
        [ 0.9215, -0.1113,  1.5625],
        [ 0.7111,  0.9540,  0.1860],
        [ 0.8744,  0.4614,  1.2320]])


In [18]:
# Get its size:
def get_size(x):
    # torch.Size is in fact a tuple, so it supports all tuple operations.
    print(x.size())
    
get_size(x)

torch.Size([5, 3])


### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [22]:
# Addition: syntax 1
def torch_add(x):
    y = torch.rand(5, 3)
    print(x + y)
    return y
    
# Addition: syntax 2
def torch_add2(x, y):
    print(torch.add(x, y))
    
# Addition: providing an output tensor as argument
def torch_add3(x, y):
    result = torch.empty(5, 3)
    torch.add(x, y, out=result)
    print(result)
    
# Addition: in-place
def torch_add4(x, y):
    # adds x to y
    y.add_(x)
    print(y)
    
y = torch_add(x)
torch_add2(x, y)
torch_add3(x, y)

# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
torch_add4(x, y)

tensor([[ 0.5787,  0.4992,  2.1081],
        [ 0.2428,  0.3807, -1.7404],
        [ 1.0854,  0.6894,  2.3179],
        [ 1.6872,  1.0199,  1.0772],
        [ 1.2204,  1.1939,  1.9060]])
tensor([[ 0.5787,  0.4992,  2.1081],
        [ 0.2428,  0.3807, -1.7404],
        [ 1.0854,  0.6894,  2.3179],
        [ 1.6872,  1.0199,  1.0772],
        [ 1.2204,  1.1939,  1.9060]])
tensor([[ 0.5787,  0.4992,  2.1081],
        [ 0.2428,  0.3807, -1.7404],
        [ 1.0854,  0.6894,  2.3179],
        [ 1.6872,  1.0199,  1.0772],
        [ 1.2204,  1.1939,  1.9060]])
tensor([[ 0.5787,  0.4992,  2.1081],
        [ 0.2428,  0.3807, -1.7404],
        [ 1.0854,  0.6894,  2.3179],
        [ 1.6872,  1.0199,  1.0772],
        [ 1.2204,  1.1939,  1.9060]])


In [23]:
print(x[:, 1])

tensor([-0.1209, -0.4896, -0.1113,  0.9540,  0.4614])


In [24]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
def torch_resize():
    x = torch.randn(4, 4)
    y = x.view(16)
    z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
    print(x.size(), y.size(), z.size())

torch_resize()

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [25]:
# If you have a one element tensor, use .item() to get the value as a Python number
def torch_item():
    x = torch.randn(1)
    print(x)
    print(x.item())
    
torch_item()

tensor([0.4473])
0.44726213812828064


### NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [28]:
# Converting a Torch Tensor to a NumPy Array
def covert_torch():
    a = torch.ones(5)
    print(a)
    return a

def convert_numpy(a):
    b = a.numpy()
    print(b)
    return b
    
a = covert_torch()
b = convert_numpy(a)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [29]:
# See how the numpy array changed in value.
def add_torch_numpy():
    a.add_(1)
    print(a)
    print(b)

add_torch_numpy()

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [30]:
# Converting NumPy Array to Torch Tensor
# See how changing the np array changed the Torch Tensor automatically
def convert_numpy2():
    import numpy as np
    a = np.ones(5)
    b = torch.from_numpy(a)
    np.add(a, 1, out=a)
    print(a)
    print(b)
    
# All the Tensors on the CPU except a CharTensor support converting to NumPy and back.
convert_numpy2()

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [31]:
def cuda_tensor():
    # let us run this cell only if CUDA is available
    # We will use ``torch.device`` objects to move tensors in and out of GPU
    if torch.cuda.is_available():
        device = torch.device("cuda")          # a CUDA device object
        y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
        x = x.to(device)                       # or just use strings ``.to("cuda")``
        z = x + y
        print(z)
        print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
        
cuda_tensor()